tunnel: dev-mycrocloud
credentials-file: ~/.cloudflared/43fe07ba-b0d1-460d-a01e-c4df25be645d.json     

ingress:
  - hostname: api.smashup1805.dpdns.org
    # service: http://localhost:5279
    service: http://raspberrypi.local:8080
  - hostname: slack-integration-api-2.smashup1805.dpdns.org
    # service: http://localhost:8082
    service: http://raspberrypi.local:8082
  - service: http_status:404