version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "src/Services/WebApp/WebApp.Admin"
      - "src/Services/WebApp/Api"
      - "src/Services/WebApp/WebApp.Gateway"
      - "src/Services/WebApp/Api.Domain"
      - "src/Services/WebApp/WebApp.FunctionInvoker"
      - "src/Services/WebApp/WebApp.FunctionShared"
      - "src/Services/WebApp/Api.Infrastructure"
      - "src/Services/WebApp/Api.Migrations"
      - "src/Services/WebApp/WebApp.MigrationTest"
      - "src/Services/WebApp/WebApp.SlackIntegrationApi"
      - "src/Services/WebApp/WebApp.UnitTest"

    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "src/Web"
      - "src/WebEditor"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:

      interval: "daily"
