all:
  vars:
    aws_region: ap-northeast-1
    aws_profile: default
  hosts:
    server:
      ansible_host: YOUR_SERVER_IP_HERE
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id
      aws_region: ap-northeast-1
      aws_profile: default
