host: mycrocloud.info
gateway_server_name: ~^apigw-\d+\.mycrocloud\.info$

web:
  replicaCount: 1
  containerPort: 80
  image:
    repository: ghcr.io/mycrocloud/mycrocloud-web
    tag: dev
  imagePullSecret: ghcr-secret
  service:
    type: ClusterIP
    port: 80

api:
  replicaCount: 2
  containerPort: 8080
  image:
    repository: ghcr.io/mycrocloud/mycrocloud-api
    tag: dev
  imagePullSecret: ghcr-secret
  service:
    type: ClusterIP
    port: 80
  secretEnv:
    ConnectionStrings__DefaultConnection: ""
    ConnectionStrings__RabbitMq: ""
    OAuthApps__GitHub__ClientSecret: ""
    AppIntegrations__GitHubWebhook__Config__Secret: ""
    Elasticsearch__Password: ""

gateway:
  replicaCount: 2
  containerPort: 8080
  imagePullSecret: ghcr-secret
  image:
    repository: ghcr.io/mycrocloud/mycrocloud-gateway
    tag: dev
  service:
    type: ClusterIP
    port: 80
  secretEnv:
    ConnectionStrings__DefaultConnection: ""
    ConnectionStrings__Redis: ""