name: monitoring
services:
  seq:
    image: datalust/seq
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QAqKAm8HUhk57veOi0Xed3JkO1k/+YqE4lCQgshVuXOUhytxYKBNfRsWYjThLyN/YIbTDpXOJQS8yHnnmOTz1kKucbNx//2uAxfzTcmGYjj+
    networks:
      - mycrocloud

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: "host"
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - '--nginx.scrape-uri=http://lb:8080/stub_status'
    ports:
      - "9113:9113"
    networks:
      - mycrocloud
    restart: unless-stopped

volumes:
  seq-data:
  prometheus_data:

networks:
  mycrocloud:
    external: true