all:
  hosts:
    server:
      ansible_host: "{{ server_host }}"
      ansible_user: "{{ server_user | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ ssh_key_file }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
