name: CI/CD Deployment/Fluentd

on:
  push:
    branches:
      - main
    paths:
      - "src/Services/WebApp/Deployment/fluentd/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    with:
      image-name: ${{ github.repository }}-deployment-fluentd
      work-dir: src/Services/WebApp/Deployment/fluentd
      dockerfile: Dockerfile
      service: fluentd
      namespace: deployment
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
