name: Deploy all services

on:
  workflow_dispatch:
    inputs:
      service_group:
        description: Service group to deploy
        required: true
        default: all
        type: choice
        options:
          - all
          - core
          - webapp
          - monitoring

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      group: deploy-${{ inputs.service_group || 'all' }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy all services
        uses: ./.github/actions/deploy-action
        with:
          server-host: ${{ vars.SERVER_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          service-group: ${{ inputs.service_group }}
          aws-iam-role: ${{ vars.AWS_IAM_ROLE_GITHUB_ACTIONS_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
