name: CI/CD Deployment/Builder

on:
  push:
    branches:
      - main
    paths:
      - "src/Services/WebApp/Deployment/builder/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    with:
      image-name: ${{ github.repository }}-deployment-builder
      work-dir: src/Services/WebApp/Deployment/builder
      dockerfile: Dockerfile
      pull-only: true
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
