name: CI/CD Function Invoker

on:
  push:
    branches:
      - main
    paths:
      - 'src/Services/WebApp/Api.Domain/**'
      - 'src/Services/WebApp/WebApp.Infrastructure/**'
      - 'src/Services/WebApp/WebApp.FunctionShared/**'
      - 'src/Services/WebApp/WebApp.FunctionInvoker/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      image-name: ${{ github.repository }}-function-invoker
      work-dir: src/Services/WebApp
      dockerfile: WebApp.FunctionInvoker/Dockerfile
      pull-only: true
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
