name: CI/CD Gateway

on:
  push:
    branches:
      - main
    paths:
      - "src/pkg/webapp/gateway/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      image-name: ${{ github.repository }}-gateway
      work-dir: src/pkg/webapp/gateway
      dockerfile: Dockerfile
      service: gateway
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
