name: CI/CD Web

on:
  push:
    branches:
      - main
    paths:
      - "src/Web/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-deploy.yml
    with:
      image-name: ${{ github.repository }}-web
      work-dir: src/Web
      dockerfile: Dockerfile
      service: web
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
