global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus self-metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Node exporter metrics

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: <GRAFANA_CLOUD_USER_ID>
      password: <GRAFANA_CLOUD_API_KEY>